---
############
#Add objects
############
- include: bigip_node/add_node.yml 
  vars: 
    - host: "10.1.20.15" 
    - name: "member1" 
    - monitor: "/Common/icmp"
  when: state == "present"

- include: bigip_node/add_node.yml 
  vars: 
    - host: "10.1.20.16" 
    - name: "member2" 
    - monitor: "/Common/icmp"
  when: state == "present"
  
- include: bigip_pool/manage_pool.yml 
  vars: 
    - name: "pool1"
    - monitor: "/Common/http_head_f5"
  when: state == "present"
  
- include: bigip_pool_member/manage_members.yml 
  vars: 
    - host: "member1" 
    - pool: "pool1"
    - port: "8080"
    - session_state: "enabled"
    - monitor_state: "enabled"
  when: state == "present"  

- include: bigip_pool_member/manage_members.yml 
  vars: 
    - host: "member2" 
    - pool: "pool1"
    - port: "8080"
    - session_state: "enabled"
    - monitor_state: "enabled"
  when: state == "present"
  
- include: bigip_irule/manage_irule.yml
  when: state == "present"

- include: bigip_virtual_server/manage_vip.yml 
  vars:
    - description: "foo-vip" 
    - destination: "10.1.10.18" 
    - name: "vip1" 
    - pool: "pool1" 
    - port: "80" 
    - snat: "Automap"
    - all_profiles: "http"
    - all_rules: "Bodgeit_Rewrite"
  when: state == "present"


###############
#Remove objects
###############

- include: bigip_virtual_server/manage_vip.yml
  vars:
    - description: "foo-vip" 
    - destination: "10.1.10.18" 
    - name: "vip1" 
    - pool: "pool1" 
    - port: "80" 
    - snat: "Automap"
    - all_profiles: "http"
    - all_rules: "Bodgeit_Rewrite"
  when: state == "absent"

- include: bigip_irule/manage_irule.yml
  when: state == "absent"

- include: bigip_pool/manage_pool.yml 
  vars: 
    - name: "pool1" 
    - monitor: "/Common/http_head_f5"
  when: state == "absent"

- include: bigip_node/remove_node.yml 
  vars:
    - name: "member1" 
    - monitor: "/Common/icmp"
  when: state == "absent"

- include: bigip_node/remove_node.yml 
  vars:
    - name: "member2" 
    - monitor: "/Common/icmp"
  when: state == "absent"
  
...
